name: Build ROM

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
 
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        make -j2
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: bious-dump.gba
